GCC=gcc
GCCC=gcc -c
SRCDIR=src
HEADDIR=include
LIBDIR=lib
 
CFLAGS= -W -Wall $(shell sdl2-config --cflags)
LDFLAGS=-I include -L lib -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lpthread

 
main:
	GCC $(SRCDIR)/main.c -o bin/prog $(LDFLAGS)

clean:
	del $(LIBDIR)\*.o